name: social_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  line_icons:
  flutter_svg: ^2.0.9
  animate_do: 
  bubble: 
  badges:
  firebase_core: ^2.22.0
  firebase_messaging: ^14.2.0
  # flutter_secure_storage: ^9.0.0
  form_field_validator: ^1.1.0
  http: ^0.13.3
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  # photo_manager: ^1.2.5
  carousel_slider: ^4.0.0
  shimmer: ^3.0.0
  timeago: ^3.6.0
  cached_network_image: ^3.2.0
  socket_io_client: ^2.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  cloudinary_public: ^0.23.1
  get_time_ago: ^1.2.5
  intl: ^0.18.1
  # cached_video_player: ^2.0.4
  # chewie: ^1.0.0
  # video_player: ^2.6.0
  dots_indicator:
  internet_connection_checker: ^1.0.0+1
  share_plus: ^7.2.1
  gallery_saver: ^2.3.2
  story_view: ^0.16.0
  swipe_to: ^1.0.2
  uuid: ^3.0.1
  emoji_picker_flutter: ^1.6.3
  audioplayers: ^5.2.0
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  get_storage: ^2.0.3
  flutter_riverpod: ^2.4.5
  dartz: ^0.10.1
  flutter_stripe: ^9.4.0
  dio: ^5.3.3
  lottie: ^2.6.0
  phosphor_flutter: ^2.0.1
  i18n_extension: ^9.0.2
  photo_view: ^0.14.0
  # device_info_plus: ^9.1.0
  font_awesome_flutter: ^10.6.0
  youtube_player_flutter: ^8.1.2
  chewie: ^1.7.1
  video_player: ^2.8.1
  photo_manager: ^3.0.0-dev.2
  just_audio: ^0.9.36
  flutter_webrtc_wrapper: ^1.0.2
  snippet_coder_utils: ^1.0.15
  flutter_blurhash: ^0.8.2

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/img/
    - assets/languages/
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Allison
      fonts:
        - asset: assets/fonts/Allison-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf
