name: social_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  line_icons:
  flutter_svg: ^1.1.6
  animate_do: 
  bubble: 
  badges:
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  flutter_secure_storage: ^6.1.0
  form_field_validator: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+9
  permission_handler: ^9.2.0
  pin_code_fields: ^7.3.0
  # photo_manager: ^2.0.8
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  timeago: ^3.2.2
  cached_network_image: ^3.2.0
  socket_io_client: ^2.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  cloudinary_public: ^0.20.0  
  get_time_ago: ^1.1.6
  intl: ^0.17.0
  cached_video_player: ^2.0.3
  chewie: 
  video_player: ^2.4.7
  dots_indicator:
  internet_connection_checker: ^0.0.1+4
  share_plus: ^6.3.0
  gallery_saver: ^2.3.2
  # story_view: ^0.15.0
  swipe_to: ^1.0.2
  uuid: ^3.0.6
  emoji_picker_flutter: ^1.3.0
  audioplayers: ^1.0.1
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  get_storage: ^2.0.3
  flutter_riverpod: ^2.0.0-dev.9
  dartz: ^0.10.1
  flutter_paypal_checkout: ^1.0.1
  flutter_stripe: ^9.4.0
  dio: ^4.0.6
  lottie: ^2.6.0
  phosphor_flutter: ^1.3.1
  i18n_extension: ^8.0.0
  photo_view: ^0.14.0
  device_info_plus: ^8.2.2

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/img/
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Allison
      fonts:
        - asset: assets/fonts/Allison-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf
