// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJREqnLmO_zXitLrc6aoyYsbKKadtLiz0',
    appId: '1:774350209960:web:3ff9400a5a26c9f2ddd39d',
    messagingSenderId: '774350209960',
    projectId: 'shop-app-1e566',
    authDomain: 'shop-app-1e566.firebaseapp.com',
    storageBucket: 'shop-app-1e566.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIm6EBars-KWGJf6NFYfJp6JRZoVg-U1o',
    appId: '1:774350209960:android:320d36cafdb5c21dddd39d',
    messagingSenderId: '774350209960',
    projectId: 'shop-app-1e566',
    storageBucket: 'shop-app-1e566.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPo6AsSbBTQoejSEMzs_ycHZJ8GUGGYFY',
    appId: '1:774350209960:ios:63e465cc50124b6dddd39d',
    messagingSenderId: '774350209960',
    projectId: 'shop-app-1e566',
    storageBucket: 'shop-app-1e566.appspot.com',
    iosClientId: '774350209960-5h29ueqkihbaapkfahpjg8e9qdgk2l5l.apps.googleusercontent.com',
    iosBundleId: 'com.mohammedrdaly.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPo6AsSbBTQoejSEMzs_ycHZJ8GUGGYFY',
    appId: '1:774350209960:ios:6a51df375756c681ddd39d',
    messagingSenderId: '774350209960',
    projectId: 'shop-app-1e566',
    storageBucket: 'shop-app-1e566.appspot.com',
    iosClientId: '774350209960-vk6hq7maabml7bsmhnm28fthouv7fujf.apps.googleusercontent.com',
    iosBundleId: 'com.mohammedrdaly.shopApp.RunnerTests',
  );
}
