// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK263wht4uQjAGdOrLZOoEdQ7IWt2bqJU',
    appId: '1:324903671024:web:632ebf07e153e672479e35',
    messagingSenderId: '324903671024',
    projectId: 'social-app-300c9',
    authDomain: 'social-app-300c9.firebaseapp.com',
    storageBucket: 'social-app-300c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSVw-5g4qyJ8LOMojPTvE8d11SJzaCtjQ',
    appId: '1:324903671024:android:60d753d83262c812479e35',
    messagingSenderId: '324903671024',
    projectId: 'social-app-300c9',
    storageBucket: 'social-app-300c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAssXIgGnEAE21uYIKlzc8yro_R2Z6GDiM',
    appId: '1:324903671024:ios:1c606a48b48035ac479e35',
    messagingSenderId: '324903671024',
    projectId: 'social-app-300c9',
    storageBucket: 'social-app-300c9.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAssXIgGnEAE21uYIKlzc8yro_R2Z6GDiM',
    appId: '1:324903671024:ios:1c606a48b48035ac479e35',
    messagingSenderId: '324903671024',
    projectId: 'social-app-300c9',
    storageBucket: 'social-app-300c9.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );
}
